### ISSUE TITLE
USER STORY: Recover password

### ISSUE THREAD

**Issue by barkode** [barkode/pp5#26]
As a Site User, I want to be able to **easily recover my password if I forget it** so that I can **regain access to my account**.

### **Acceptance Criteria:**

- [ ] Users can request a password reset via their registered email.
- [ ]  A valid reset link is sent, allowing the user to reset their password.

### **Tasks:**

- [ ] Implement a password recovery form and process.
- [ ] Send a password reset link to the user’s email.
