### ISSUE TITLE
USER STORY: Estimated delivery date

### ISSUE THREAD

**Issue by barkode** [barkode/pp5#37]
As a **Shopper**, I want to be able to **see an estimated delivery date before completing the purchase** so that I **know when to expect my order**.

### **Acceptance Criteria:**

- [ ] The estimated delivery date should display before payment submission.
- [ ]  The date should update if the user changes their delivery address.

### **Tasks:**

- [ ] Calculate estimated delivery dates based on user location.
- [ ] Display delivery estimates dynamically at checkout.
