### ISSUE TITLE
USER STORY: Add new products to the store

### ISSUE THREAD

**Issue by barkode** [barkode/pp5#38]
As a **Store Owner**, I want to be able to **add new products to the store** so that I can **keep my inventory updated**.

### **Acceptance Criteria:**

- [ ] New products are saved and display on the user-facing site.
- [ ]  Required fields are validated before submission.

### **Tasks:**

- [ ] Create an admin form for adding new products.
- [ ] Enable uploading images and setting product details.
