### ISSUE TITLE
USER STORY: Special offers, product arrivals, and upcoming sales emeails

### ISSUE THREAD

**Issue by barkode** [barkode/pp5#45]
As a **Shopper**, I want to be able to **receive emails for special offers, new product arrivals, and upcoming sales** so that I can **stay updated on promotions**.

### **Acceptance Criteria:**

- [ ] Emails are sent to subscribed users for special offers, new products, and sales.
- [ ]  Users can subscribe/unsubscribe to promotional emails via account settings.

### **Tasks:**

- [ ] Create automated email templates for promotional notifications.
- [ ] Set up user preferences for email subscription management.
