### ISSUE TITLE
USER STORY: Seasonal promotions on the homepage

### ISSUE THREAD

**Issue by barkode** [barkode/pp5#47]
As a **Shopper**, I want to be able to **see seasonal promotions on the homepage** so that I can **take advantage of timely discounts**.

### **Acceptance Criteria:**

- [ ] Promotions are displayed prominently on the homepage.
- [ ] Banner is clickable and redirects users to the promotional category or page.
- [ ] Promotions end automatically after the set end date.

### **Tasks:**

- [ ] Design a promotions banner on the homepage.
- [ ] Allow admin users to set up promotional banners with start and end dates.
