### ISSUE TITLE
USER STORY: Discount codes during checkout

### ISSUE THREAD

**Issue by barkode** [barkode/pp5#48]
As a **Shopper**, I want to be able to **apply discount codes during checkout** so that I can **receive discounts on my purchases**.

### **Acceptance Criteria:**

- [ ] Users can enter a discount code and see an updated total if valid.
- [ ] Invalid codes display an error message.
- [ ] Only one discount code can be applied per order.

### **Tasks:**

- [ ] Add a discount code input field at checkout.
- [ ] Implement validation for discount codes, showing applicable discount.
