### ISSUE TITLE
USER STORY: Discount duration manage

### ISSUE THREAD

**Issue by barkode** [barkode/pp5#52]
As a **Store Owner**, I want to be able to **manage the duration of each discount** so that **promotions are only active for specified times**.

### **Acceptance Criteria:**

- [ ] Discounts are automatically applied on the start date and removed after the end date.
- [ ] Admins can manually adjust the duration of active discounts.

### **Tasks:**

- [ ] Add start and end date options for each promotion in the admin panel.
- [ ] Automate discount removal when the end date is reached.
